# This is a basic workflow to help you get started with Actions
name: Auto-doc

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "base" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build:
    # name: Auto-Documentation
    runs-on: ubuntu-latest
    
    steps:  # steps for the auto-documentation

      #- uses: actions/checkout@master   # checks out repo so workflow can access it ----TEST THIS----
      #- name: setup virtual environment
      #  run: |
      #    virtualenv venv
      #    venv\Scripts\activate


      # this part makes sure sphinx is installed
      - uses: actions/checkout@master   # checks out repo so workflow can access it ----TEST THIS----
      - uses: actions/setup-python@v3   # sets up a python environment for use
      - name: Install dependencies
        run: |                                  
          python -m pip install --upgrade pip
          pip install -U sphinx
          pip install sphinx-autodoc-typehints
          pip install sphinx_rtd_theme

          pip install invoke
          invoke --version 

      
      # this part will call sphinx and automatically answer the prompts
      - uses: actions/checkout@master   
      - uses: actions/setup-python@v3   
      - name: Run Sphinx & Auto-fill Prompts
        run: |
          invoke answers

      # this part automatically generates the rst files
      - uses: actions/checkout@master   
      - uses: actions/setup-python@v3   
      - name: Build
        run: |
          sphinx-build -b html docs/source/ docs/build/html
          cd docs
          make html


      #- name: Run a one-line script
      #  run: echo Hello, world!
